vim.cmd("set expandtab")
vim.cmd("set tabstop=3")
vim.cmd("set softtabstop=3")
vim.cmd("set shiftwidth=3")
vim.cmd("set number relativenumber")
vim.cmd("set shell=powershell")
vim.cmd("set shellcmdflag=-command")
vim.cmd("set shellquote=\"")
vim.cmd("set shellxquote=")
vim.g.mapleader = " "
